### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by chrisjcalderon** [jgodson/shopify-script-creator#109]
Is there a plan for this fantastic project given that Shopify as plans to deprecate/remove Shopify Scripts in favor of using Shopify Functions?

**Comment by jgodson** [comment]
Hi Chris, unfortunately the usefulness of this app will end with that deprecation.

I have no plans currently to make a similar Shopify Functions equivalent. That said, I believe there are some apps that are offering this (and more?) functionality like [checkout blocks](https://apps.shopify.com/checkout-blocks)
