### ISSUE TITLE
Bundle Discounts

### ISSUE THREAD

**Issue by chrisjcalderon** [jgodson/shopify-script-creator#11]
Hi Jason,

I'm having a problem with the bundle discount.  When it runs by itself (it is the only campaign) it runs, however when is combined with another, it does not apply the discounts.

I have the script configured to do this:

1) 5% for customer tag Member (this always runs)
2) Bundle - buy a table and a paddle and get an additional 5% off

If it runs first, then it applies the discounts - if it runs after any other campaign, then it doesn't  - and it does not use the  discounted item selector (discount by script) - so it should work, I think

Thanks!

**Comment by jgodson** [comment]
Thanks for letting me know. I'll look at this as soon as I have some time!

**Comment by jgodson** [comment]
Actually, I just noticed that I purposely excluded already discounted items from bundles. I could definitely make this an option instead.

**Comment by chrisjcalderon** [comment]
Thanks! I have the always on 5% discount for members and was experimenting with bundles - I can see why you would like to exclude bundles from being part of multiple discounts - IMO, this rule should apply to bundles only (so a bundle is not further discounted by another)

**Comment by jimovonz** [comment]
It would be really nice to have some sort of priority order and qualifier rules based on whether or not previous campaigns applied discounts. This would be useful for when a product is potentially involved with multiple campaigns and you don't want multiple discounts applied

**Comment by jgodson** [comment]
Hey @jimovonz, there is a Line Item Qualifier that you can use to check if an item has been discounted

![alt](https://screenshot.click/10-29-v7k7k-tv3os.jpg)

**Comment by miahcodes** [comment]
Hi @jgodson, 

We’re doing a tiered product bundling with the following campains in one script:
A. Buy 1 Top 1 Bottom + 1 any item at 50% off,
B. Buy 1 Top + 1 Bottom 40% off,
C. Buy 1 Top 30% off
How can I make Campaigns A & B apply only to non-discounted items?

Please see attached exported campaigns below.

[SSC-V0.26.0-script-5527851.txt](https://github.com/jgodson/shopify-script-creator/files/4592687/SSC-V0.26.0-script-5527851.txt)

I've also been encountering bugs that even if I only added 1 item quantity to cart, 2 gets added and even when I try to update the quantity it seems that the script force requires 2 quantities.

Would appreciate any help. Thank you.

**Comment by jgodson** [comment]
Hey @miahcodes, sorry I've been a bit swamped lately and haven't had time to respond. 

> How can I make Campaigns A & B apply only to non-discounted items?
Discounted by other campaigns in the script?

I will try to look into that bug you mentioned this weekend 🤞

**Comment by miahcodes** [comment]
@jgodson hey man. thanks for replying. just wanted to know if you were able to give the issue a check? would love to jump in on a call if it'd give more clarity on the issue. Thanks! 🙇🏻‍♂️

**Comment by jgodson** [comment]
@miahcodes I haven't had a chance to look into the bug yet, however for your Buy X Get X, you can use the `Multi-select - Meets All Conditions` qualifier and then add this qualifier to make sure that items that have already been discounted by another campaign will not count towards the get item or the buy item (or both).

![alt](https://camo.githubusercontent.com/67b07e39dc59aa64fa67f6178adbb9c18fe00249/68747470733a2f2f73637265656e73686f742e636c69636b2f31302d32392d76376b376b2d7476336f732e6a7067)

**Comment by chrisjcalderon** [comment]
Just a comment, not an issue. I wanted to thank Jason for such a fantastic project, I have been using it for a while now in combination with a liquid snippet/section to configure surface promotions to customers (so they are aware of what is available and easily add promos to their carts) - and it works fantastic!

**Comment by erictktoh** [comment]
Hi Jason, my name is Eric and nice to meet you. May I ask you a question if your Shopify Script Editor is able to set a mix bundle of 4 items at new price of $100 for instance?

Cheers.

**Comment by jgodson** [comment]
@erictktoh no, there's no way to discount to a specific price like that. I did look at doing [that at one time](https://github.com/jgodson/shopify-script-creator/pull/4), but I recall it did not work properly (or as expected at least) in some situations so I never did add it in.

**Comment by erictktoh** [comment]
> @erictktoh no, there's no way to discount to a specific price like that. I did look at doing [that at one time](https://github.com/jgodson/shopify-script-creator/pull/4), but I recall it did not work properly (or as expected at least) in some situations so I never did add it in.

@jgodson thanks for your reply, got it. :)
