### ISSUE TITLE
Conditional Discount Campaign with Percentage Discount Causes Permalinks to Error out

### ISSUE THREAD

**Issue by Mistermo716** [jgodson/shopify-script-creator#17]
So If a campaign of type conditional discount is combined with a percentage discount it causes permalinks to stop working. I have tried that specific campaign in many scenarios and it has consistently caused this issue.

**Comment by jgodson** [comment]
Do you know if there is a $0 discount being applied in your case or no discount at all?

**Comment by Mistermo716** [comment]
> Do you know if there is a $0 discount being applied in your case or no discount at all?

So, I assumed it was because of another campaign targeting a bundle at 0.0001% then later giving the bundled discount through a conditional discount. However, I have had this issue with a simple conditional discount targeting one item at 10% off. To make sure it is not a problem caused by other campaigns, I generated a script with one conditional (with a percentage discount) campaign and still had permalinks error out.

**Comment by jgodson** [comment]
Hmm that's definitely odd. I have seen this behavior when a discount gets applied that ends up being $0. If there is an actual discount applied (>= 0.01) then that seems like it's probably a separate issue
