### ISSUE TITLE
Hide payment gateway based on selected shipping method

### ISSUE THREAD

**Issue by josephws** [jgodson/shopify-script-creator#24]
I am trying to generate a script that hides a payment gateway based on the selected shipping method

Please advise.

**Comment by jgodson** [comment]
Hi @josephws, unfortunately within Shopify scripts it's not possible to know what the selected shipping method was.

**Comment by josephws** [comment]
@jgodson I saw one store that implemented this feature, I am trying to do the same, please check https://en.oudmilano.com/1771077696/checkouts/d3c2ced5448305e65f5d78ab36589ea0?step=shipping_method

**Comment by josephws** [comment]
@jgodson I see that they are using javascript to accomplish that by passing a flag that determines the selected shipping method:

  **| var liquid_Checkout_com = false;
  | var liquid_COD = false;**


```
  |$(document).on("page:load page:change", function() {
  | var liquid_Checkout_com = false;
  | var liquid_COD = false;
  |  
  | // DATA LIQUID
  |  
  |  
  | liquid_COD = true;
  |  
  |  
  |  
  |  
  | var page_type = '';
  | if (Shopify.Checkout.step == "payment_method" ) {
  | page_type = 'payment';
  | } else if ( Shopify.Checkout.step == "shipping_method" ) {
  | page_type = 'shipping';
  | } else if ( Shopify.Checkout.step == "contact_information" ) {
  | page_type = 'customer';
  | }
  |  
  |  
  | if (page_type == 'payment') {
  | func_hide();
  | }
  |  
  |  
  | function func_click(Elem) {
  | Array.prototype.forEach.call(document.querySelectorAll(".radio__label__primary"), function(e) {
  | if(e.textContent.indexOf(Elem) > -1) {
  | e.click();
  | }
  | });
  | $("div[data-select-gateway]").each( function() {
  | $(this).hide();
  | $(this).addClass("this_remove");
  | if ( $(this).find(".radio__label__primary").html().indexOf(Elem) > -1 ) {
  | $(this).show();
  | $(this).removeClass("this_remove");
  | $(this).find(".radio__label__primary")[0].click();
  | }
  | });
  |  
  | $(".this_remove").remove();
  | }
  |  
  |  
  |  
  | function func_hide() {
  | var Shipping_method = '';
  | var ar_COD = "الدفع عند الاستلام";
  |  
  |  
  | if ( $("html").attr("dir") == "rtl" ) {
  | if ( liquid_COD ) {
  | Shipping_method = ar_COD;
  | func_click(ar_COD);
  |  
  | } else if ( liquid_Checkout_com ) {
  | Shipping_method = 'Checkout.com (Offsite)';
  | func_click('Checkout.com (Offsite)');
  | }
  |  
  | } else {
  | if ( liquid_COD ) {
  | Shipping_method = 'Cash on Delivery (COD)';
  | func_click('Cash on Delivery (COD)');
  |  
  | } else if ( liquid_Checkout_com ) {
  | Shipping_method = 'Checkout.com (Offsite)';
  | func_click('Checkout.com (Offsite)');
  | }
  |  
  | }
  |  
  | }
```

**Comment by jgodson** [comment]
Was just about to come back and say that it appears to be accomplished via JavaScript 🙂

**Comment by josephws** [comment]
> Was just about to come back and say that it appears to be accomplished via JavaScript 🙂

I am ready to pay you if you can implement on my store, I have a ShopifyPlus store. 

Kindly let me know if you are interested.

**Comment by jgodson** [comment]
While I appreciate the offer, I'm not currently available for implementing this on any shops. 

I can tell you that you would need to add similar code to your `checkout.liquid` file within your theme's `Layout` folder to accomplish this. I wouldn't be able to get much more specific than that though as it depends on the current code within that file as well as if you have that file available to you currently. You may need to have that enabled if you don't have already have it.
