### ISSUE TITLE
Discount on payment methods

### ISSUE THREAD

**Issue by isoftjhang** [jgodson/shopify-script-creator#27]
Hi

Need to create a [script of Discount](https://www.imran.xyz) when payment method selected to increase prepayment encouragement.  When the user selects a credit card instead of COD, some percentage discount to that customer. 

You done a great job can work in it.

**Comment by jgodson** [comment]
Hello, thanks for the suggestion!

It's not possible within scripts to discount based on payment or shipping methods chosen unfortunately. There's nothing in the [Shopify Scripts API](https://help.shopify.com/en/manual/apps/apps-by-shopify/script-editor/shopify-scripts) that allows for that, so I'm not able to help you out on that one. Sorry about that!

**Comment by sibelius** [comment]
hey @jgodson is there another approach to apply a discount based on a payment method?

**Comment by kirpalsingh17** [comment]
Hey @isoftjhang ,

Shopify does not offer support for this particular feature, but I can assist you in comprehending how to accomplish it.

- To achieve this, you will need to develop a Shopify checkout extension app.
- The app will verify if the selected payment method matches the criteria and then add a discount code accordingly.
[https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/targets/payments/purchase-checkout-payment-method-list-render-after](url)

selectedPaymentOptions
applyDiscountCodeChange

These two hooks primarily need to be used.

Happy Coding :)

**Comment by tailwindtom** [comment]
we created a payment app that can do it. :-) check the app in action here: https://www.hifi-profis-da.de/ just put something in the checkout and see the 2% discount on vorkasse.

**Comment by sibelius** [comment]
is the payment app open sourced?

why only on shopify plus?

**Comment by tailwindtom** [comment]
The app is capable of moving and hiding payment methods without a plus subscription, but unfortunately for the function to apply that discount to the payment method we use a hook that's only available for Shopify plus / checkout ui.

**Comment by sibelius** [comment]
what hooks ?

**Comment by kirpalsingh17** [comment]
@sibelius Hooks consider events in checkout extension that Shopify support like this
https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/react-hooks

**Comment by kirpalsingh17** [comment]
@tailwindtom Can you please share me installation link of your app?
also, May I try it in the development store although I have Shopify plus?

**Comment by tailwindtom** [comment]
@kirpalsingh17 right now there is no real interface in our app which is why it would make no sense to share a link yet. but you can see how it works in the demo link i posted here and soon it will be on the shopify app store. once its approved by shopify - i will post it here. if you need this feature before the official release you can contact me with your plus domain and we can send you a custom offer for that.

**Comment by PerfectoCayabyab** [comment]
> @kirpalsingh17 right now there is no real interface in our app which is why it would make no sense to share a link yet. but you can see how it works in the demo link i posted here and soon it will be on the shopify app store. once its approved by shopify - i will post it here. if you need this feature before the official release you can contact me with your plus domain and we can send you a custom offer for that.

The problem on this is the customer will know the discount code and use it even if it's not credit card or vice versa

**Comment by kirpalsingh17** [comment]
Hi @tailwindtom  Thanks, I am able to achieve same with Checkout extension.

`function Extension() {
  const [showError, setShowError] = useState(false);
  const [codPayment, setCodPayment] = useState(false);
  const options = useSelectedPaymentOptions();
  const applyDiscountCodeChange = useApplyDiscountCodeChange();

  useEffect(() => {
    const isCodPaymentDesired = options.some((option) => option.type === 'paymentOnDelivery');
    
    if (isCodPaymentDesired !== codPayment) {
      if (isCodPaymentDesired) {
        const result = applyDiscountCodeChange({
          type: 'removeDiscountCode',
          code: 'PREPAID',
        });
        console.log('applyDiscountCodeChange removeDiscountCode result', result);
      } else {
        const result = applyDiscountCodeChange({
          type: 'addDiscountCode',
          code: 'PREPAID',
        });
        console.log('applyDiscountCodeChange addDiscountCode result', result);
      }

      setCodPayment(isCodPaymentDesired);
    }
  }, [options, codPayment]);

  useBuyerJourneyIntercept(({ canBlockProgress }) => {
    return canBlockProgress && codPayment
      ? {
          behavior: 'block',
          reason: 'limited stock',
          perform: (result) => {
            if (result.behavior === 'block') {
              setShowError(true);
            }
          },
        }
      : {
          behavior: 'allow',
          perform: () => {
            setShowError(false);
          },
        };
  });

  return showError ? <Banner status="critical" title="Verify OTP" /> : null;
}`

**Comment by tailwindtom** [comment]
@kirpalsingh17 are you able to get the payment method id within your app? when there is multiple manual payment methods? thats the main issue

**Comment by kirpalsingh17** [comment]
Yes, I am able to achieve all payments method as well as selected payment method with checkout api in extension.

**Comment by tailwindtom** [comment]
Thats not the issue. The issue is: 
-> Our customer needs to be able to select the payment method in the app backend 
-> We need to send the ID, not the name to our checkout ui, applying the discount. 

if you want to we can schedule a call !

**Comment by kirpalsingh17** [comment]
Please follow the document by Shopify, https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/apis/payments

You can only pass handle and type to validated selected or available payment methods.

You can also follow Shopify functions to handle payment customisation. I am following basic requirement to apply discount based on payment method. Thanks

**Comment by tailwindtom** [comment]
We already know that and unfortunately this is the reason, why we can not proceed. This works for all payment methods, except for when there is MULTIPLE MANUAL payment methods. 

if you just want to hide and move payment methods it is easy but not for this specific case.

**Comment by kirpalsingh17** [comment]
import {
  reactExtension,
  Banner,
  useSelectedPaymentOptions,
} from '@shopify/ui-extensions-react/checkout';

export default reactExtension(
  'purchase.checkout.block.render',
  () => <Extension />,
);

function Extension() {
  const options = useSelectedPaymentOptions();

  if (
    options.some(
      (option) => option.type === 'creditCard',
    )
  ) {
    return (
      <Banner>
        All credit card transactions are secure
      </Banner>
    );
  }

  return null;
}


Have a look example above, it will return you selected payment method each time you change.

**Comment by code-ness** [comment]
async function Extension() {
  const options = useSelectedPaymentOptions();
  const applyDiscountCodeChange = useApplyDiscountCodeChange();

  if (options[0].type === "manualPayment") {
    await applyDiscountCodeChange({
      type: "addDiscountCode",
      code: "BANKWIRE",
    });
  } else {
    await applyDiscountCodeChange({
      type: "removeDiscountCode",
      code: "BANKWIRE",
    });
  }

  return null;
}

here's mine

**Comment by code-ness** [comment]
what should I return? when I apply or remove discount code?

**Comment by code-ness** [comment]
@kirpalsingh17

**Comment by kirpalsingh17** [comment]
@code-ness 

Take my prev sample code

`
function Extension() {
  const { i18n } = useApi();
  const paymentOptions = useSelectedPaymentOptions();
  const applyDiscountCodeChange = useApplyDiscountCodeChange();
  const usedDiscountCodes = useDiscountCodes();
  const { amount } = useSubtotalAmount();
  const [codPayment, setCodPayment] = useState(false);
  const [selectedDiscount, setSelectedDiscount] = useState('');
  const { cod_discount_code1,
    cod_discount_heading1,
    cod_discount_radio1,
    cod_discount_min_amount1,
    cod_discount_code2,
    cod_discount_heading2,
    cod_discount_radio2,
    cod_discount_min_amount2,
    pre_discount_code1,
    pre_discount_heading1,
    pre_discount_radio1,
    pre_discount_min_amount1,
    pre_discount_code2,
    pre_discount_heading2,
    pre_discount_radio2,
    pre_discount_min_amount2,
  } = useSettings();



  const prePaidDiscount = [
    {
      ...(pre_discount_code1 && { DiscountCode: pre_discount_code1 }),
      ...(pre_discount_heading1 && { DiscountHeading: pre_discount_heading1 }),
      ...(pre_discount_radio1 && { DiscountRadio: pre_discount_radio1 }),
      ...(pre_discount_min_amount1 && { MinmumAmount: pre_discount_min_amount1 }),
    },
    {
      ...(pre_discount_code2 && { DiscountCode: pre_discount_code2 }),
      ...(pre_discount_heading2 && { DiscountHeading: pre_discount_heading2 }),
      ...(pre_discount_radio2 && { DiscountRadio: pre_discount_radio2 }),
      ...(pre_discount_min_amount2 && { MinmumAmount: pre_discount_min_amount2 }),
    }
  ];


  const codDiscount = [
    {
      ...(cod_discount_code1 && { DiscountCode: cod_discount_code1 }),
      ...(cod_discount_heading1 && { DiscountHeading: cod_discount_heading1 }),
      ...(cod_discount_radio1 && { DiscountRadio: cod_discount_radio1 }),
      ...(cod_discount_min_amount1 && { MinmumAmount: cod_discount_min_amount1 }),
    },
    {
      ...(cod_discount_code2 && { DiscountCode: cod_discount_code2 }),
      ...(cod_discount_heading2 && { DiscountHeading: cod_discount_heading2 }),
      ...(cod_discount_radio2 && { DiscountRadio: cod_discount_radio2 }),
      ...(cod_discount_min_amount2 && { MinmumAmount: cod_discount_min_amount2 }),
    }
  ];
  
  const isEmptyObject = (obj) => {
    return Object.keys(obj).length === 0 && obj.constructor === Object;
  };


  /*
  const codDiscount = [
     {
       DiscountCode: "COD15%OFF",
       DiscountHeading: "15% off in COD",
       DiscountRadio: "Purchase @ 1000",
       MinmumAmount: 1000,
     },
     {
       DiscountCode: "COD20%OFF",
       DiscountHeading: "20% off in COD",
       DiscountRadio: "Purchase @ 2000",
       MinmumAmount: 2000,
     },
   ];
 
    const prePaidDiscount = [
     {
       DiscountCode: "PREPAID25%OFF",
       DiscountHeading: "25% off in prepaid",
       DiscountRadio: "Purchase @ 1000",
       MinmumAmount: 1000,
     },
     {
       DiscountCode: "PREPAID30%OFF",
       DiscountHeading: "30% off in prepaid",
       DiscountRadio: "Purchase @ 2000",
       MinmumAmount: 2000,
     }, 
   ];
*/
  // console.log({prePaidDiscount});

  const applyDiscountCode = (type, discount) => {
    console.log({ type, code: discount });

    if (selectedDiscount !== '') {
      applyDiscountCodeChange({ type: 'removeDiscountCode', code: selectedDiscount });
    }
    applyDiscountCodeChange({ type, code: discount });
    setSelectedDiscount(discount);
  };
  const updateDiscountCodes = (discountArray) => {
    discountArray.forEach((discount) => {
      applyDiscountCodeChange({ type: 'removeDiscountCode', code: discount.DiscountCode });
    });
  };

  useEffect(() => {
    const isCodPaymentDesired = paymentOptions.some((option) => option.type === 'paymentOnDelivery');
    if (isCodPaymentDesired !== codPayment) {
      setCodPayment(isCodPaymentDesired);
      setSelectedDiscount('');
      const updatedDiscountCodes = isCodPaymentDesired ? prePaidDiscount : codDiscount;
      updateDiscountCodes(updatedDiscountCodes);
    }
    const appliedDiscountCodes = usedDiscountCodes.map(discount => discount.code);
    const discountCodesToCheck = isCodPaymentDesired ? prePaidDiscount : codDiscount;
    const anyDiscountApplied = discountCodesToCheck.some(discount => appliedDiscountCodes.includes(discount.DiscountCode));

    // console.log({appliedDiscountCodes, anyDiscountApplied});

    if (anyDiscountApplied) {
      setSelectedDiscount('');
      updateDiscountCodes(discountCodesToCheck);
    }
  }, [paymentOptions, codPayment, usedDiscountCodes]);
  let codDiscounts = [];
  let prePaidDiscounts = [];
  if (!prePaidDiscount.every(isEmptyObject)) {
    prePaidDiscounts = prePaidDiscount;
  }
  if (!codDiscount.every(isEmptyObject)) {
    codDiscounts = codDiscount;
  }
  const selectedDiscounts  = codPayment ? codDiscounts : prePaidDiscounts;
  const filteredDiscountOptions = selectedDiscounts .filter(discount => {
    return Object.keys(discount).length !== 0;
  });

  return (
    <ChoiceList
      name="choice"
      value={selectedDiscount}
      onChange={(value) => {
        console.log(`onChange event with value: ${value + amount}`);
        applyDiscountCode('addDiscountCode', value);
      }}
    >
      <BlockStack>
        {filteredDiscountOptions.map((discount, index) => (

          <Banner title={`${discount.DiscountHeading}`} status={discount.MinmumAmount <= amount ? 'success' : 'critical'} key={index}>
            {discount.MinmumAmount > amount && (<Text size="small">{`You are just ${i18n.formatCurrency(discount.MinmumAmount - amount)} away`}</Text>)}
            <Choice disabled={discount.MinmumAmount <= amount ? false : true}
              id={discount.MinmumAmount <= amount ? discount.DiscountCode : null}>{discount.DiscountRadio}</Choice>
          </Banner>
        ))}
      </BlockStack>
    </ChoiceList>
  ); 
}`
