### ISSUE TITLE
Use Match Condition "end_with" + "start_with" Together

### ISSUE THREAD

**Issue by ryanpamplin** [jgodson/shopify-script-creator#39]
Hello - I love your software and am grateful for it!

I would like to create a Match Condition for a Cart Qualifier that checks for a match of the start or end of a given discount code.

Contains won't work for my use case, because some of my random codes contain 10, 12, 15, and 25, for example.

Is there an easy tweak I can make to the output code to quickly enable this kind of thing?

Here's an example block of code that I would like to modify to check for end_with or start_with.

CAMPAIGNS = [
  ConditionalDiscountCodeRejection.new(
    :all,
    nil,
    CodeQualifier.new(
      :does_not,
      :end_with,
      ["12", "10", "VIP", "25", "15", "AWESOME"]
    ),
    :any,
    nil,
    "Not valid during New Year's Sale."
  ),

Thank you!

**Comment by jgodson** [comment]
Hi Ryan, glad to hear the Script Creator is useful for you!

So to clarify, you'd like to check the start *and* end? If that's the case, you could use the `Multi-Select - Meets any conditions` (make sure it's the `any` one) and then add that qualifier twice, one with the `Starts with` and one with the `Ends with`. It's not perfect as you'll end up having to enter the values twice, but it should work without any code modifications!

Let me know if that helps!
