### ISSUE TITLE
Pull script creator file from shopify script editor?

### ISSUE THREAD

**Issue by JPFresh** [jgodson/shopify-script-creator#48]
Hey, I made two scripts using your wonderful script editor. I didn't realize until after the fact that you can't publish two scripts simultaneously. I also did not export my scripts from your editor originally.  

The scripts only exist within the Shopify script editor at the moment. Is it possible for me to export them in some way from Shopify so that I can import them back into your edit and combine them into one campaign?

**Comment by jgodson** [comment]
Hey @JPFresh 👋🏻.

The Script Creator export files are a much different format than the actual code that's generated. There's no way to import the generated code that you have unfortunately.
