### ISSUE TITLE
Shopify Line Items Script Editor Errors on when :discountable_total

### ISSUE THREAD

**Issue by yarnsnowman** [jgodson/shopify-script-creator#57]
Good evening! 

**In version 0.31.0 of SSC:** 
I'm seeing Shopify Line Items Script Editor syntax errors for a previously working (V0.30.0) **tiered discount**. 

This is the line I'm getting unexpected keyword syntax errors with and it seemed to be happening on the campaign initialization for tiered discounts (see attached screen recording):
" when :discountable_total"

Screen recording showing where in code/initialization the error is occurring: 
[Link to dropbox capture](https://capture.dropbox.com/DTV8wmD0RerIQmKC)

Thanks for your help!

Mike

**Comment by jgodson** [comment]
Oh, that's not good. Thanks for letting me know. I will revert to the last version until I figure out what the problem is!

**Comment by jgodson** [comment]
I've reverted the change, let me know if things are working now!

**Comment by yarnsnowman** [comment]
Thanks @jgodson ! I'll let you know if there are any issues. I appreciate your quick response.

**Comment by yarnsnowman** [comment]
Hi @jgodson !

Version 0.31.1 worked well with no syntax errors reported on the Shopify Scripts app! Thanks for the updates.

**Comment by jgodson** [comment]
Awesome. Thanks again for reporting, and for following up!
