### ISSUE TITLE
Is there a way where we can insert tags into the product order whenever the line script is activated? 

### ISSUE THREAD

**Issue by chea1tei** [jgodson/shopify-script-creator#59]
For instance, if we use the bundles discount line script, is there a way we can insert a tag into the order placed where the discount was used?
<img width="619" alt="Screenshot 2022-05-19 at 8 34 17 PM" src="https://user-images.githubusercontent.com/15363982/169294268-eba27a66-7c56-4e35-8683-a4981348c5f4.png">
?

**Comment by jgodson** [comment]
This wouldn't be possible with just scripts, but if you have access to discounts that were applies by scripts [Shopify flow[(https://apps.shopify.com/flow) may be able to tag the order based on that.

I haven't tried this myself though, so I'm not sure if that's possible.

**Comment by chea1tei** [comment]
Thanks! i've installed the shopify flow app, and it looks like it may be able to do it! just need to figure out the flow.
