### ISSUE TITLE
Tier pricing to a certain quantity and back to normal price.

### ISSUE THREAD

**Issue by chea1tei** [jgodson/shopify-script-creator#60]
Hello!

I'm looking on the tiered discount campaign.

My current tier discount is:-

BUY 1 FOR $50 ( SINGLE PACK )
BUY 2 FOR $90 ( 10% OFF ) ( DUO PACK )
BUY 3 FOR $126 ( 16% OFF ) ( TRIO PACK )

on the 4th item, i noticed the tiered discount would pick up on the tier 3 discount ( which is the 16% off ).. is it possible to make the 4th item to be on a normal price? ( TRIO + SINGLE ), and on the 5th item, ( TRIO + DUO )?

<img width="384" alt="Screenshot 2022-05-23 at 1 29 24 PM" src="https://user-images.githubusercontent.com/15363982/169749662-f0d7e562-19c2-4e40-b8d6-cb676b8a1041.png">

**Comment by jgodson** [comment]
Hello 👋🏻 

Yes the tiered discount will not "reset" once it hits the final tier. I haven't checked this myself but you could potentially do bundle discounts for each tier and use `full bundle only` for them. The trio will have to come first in the campaign list to make sure that it applies to all applicable items and the duo will handle what's left.

**Comment by chea1tei** [comment]
Hello @jgodson !

Yes, i've tried the method and it works perfectly now! :) 

Thank you!
