### ISSUE TITLE
Bundle pricing issue bug

### ISSUE THREAD

**Issue by chea1tei** [jgodson/shopify-script-creator#64]
Hello, 

We're setting up a bundle pricing of $199.99 for 2 items. The original price of an item is $109.99.  each discount item should be $9.995 if user purchase in a bundle. However on checkout, the script keeps reading it as $20 discounted instead. it should be  $19.99 ...

<img width="1280" alt="Screenshot 2022-08-04 at 9 57 21 PM" src="https://user-images.githubusercontent.com/15363982/182865259-4437d069-fac1-496f-b8e5-dd86a4304e76.png">

**Comment by jgodson** [comment]
Hi @chea1tei, thanks for the bug report. What discount are you using for the script, a fixed per item discount of 9.995?

I suspect the problem my lie here
<img width="474" alt="image" src="https://user-images.githubusercontent.com/12747574/183778499-c2357b39-1480-499a-b952-87b2654dda7d.png">

When giving it an input of 9.995 like so
<img width="474" alt="image" src="https://user-images.githubusercontent.com/12747574/183778535-a328e6a2-6bdb-4312-a6c3-0d1d5224ab02.png">

It would be `Money.new(cents: 999.5)` which may cause it to round up to 1000 (I'm not 100% sure how that works in scripts internally). You could test that theory by changing that to `Money.new(cents: amount)` and `FixedItemDiscount.new(9995, 'test')` for example.

**Comment by jgodson** [comment]
I was able to verify this today

<img width="489" alt="image" src="https://user-images.githubusercontent.com/12747574/186821083-1b80414e-7b53-4b50-b7fd-5c88c0bbe41a.png">
