### ISSUE TITLE
Line Item title

### ISSUE THREAD

**Issue by bpnorman** [jgodson/shopify-script-creator#77]
I have been using the below very basic script to apply a discount based on the line_item.variant.title. I would now like to introduce a qualifier based on a customer tag, and so, I am here trying to generate this script. I can't sort out how to use the generator to reference the variant title.  DISCOUNTED ITEM SELECTOR = Has Properties "Keys and values" seems to be the right place, but I don't think code is present to expose and reference the variant details for this to work... unless I am doing something wrong? 

Input.cart.line_items.each do |line_item|
  product = line_item.variant.product
  next if product.gift_card?
  next unless line_item.variant.title == 'Size 4 Mens'
  line_item.change_line_price(line_item.line_price * 0.80, message: "DISCOUNT APPLIED")
end

Output.cart = Input.cart

**Comment by jgodson** [comment]
Hello 👋🏻, that would not be the proper place, I haven't actually had a request to use variant title yet! It's not one of the options. Variant ID or SKU is however, if that would work?

That said, it should be super quick to add this into the script creator if you do need variant title though, I should be able to do that tonight, or sometime this weekend anyway!

**Comment by bpnorman** [comment]
That would be fantastic if you can add! I run a shoe company and basically what I am trying to do is create a rule so that loyal customers (tagged as such in Shopify) can access a specific size discount for growing kids. Adding SKUs or Variant IDs does work, but I prefer not to manage and update the script as new shoes come in. My variant titles are all based on size, so this would allow for any variant named 'Size 4 Mens' to get a discount without having to remember to keep the script current. 

Thank you for the quick response - and building this is general. This is a really powerful tool for folks like me that know very little about scripting ;)

**Comment by jgodson** [comment]
I just added it in, let me know if there are any issues!
