### ISSUE TITLE
Sort Campagins

### ISSUE THREAD

**Issue by chrisjcalderon** [jgodson/shopify-script-creator#8]
It is not an issue, some requests...

1) Ability to order the campaigns.   When creating  a script with multiple campaigns,  sometimes I don't create them necessarily in the order I want them to run (last minute changes, etc.) - the order can be important since one campaign might affect another,.

2) Is it possible to add a "add to script generation (or something like that)" checkbox  in each Campaign so only those selected will included in the generated script? This would allow us to use the tool to create and manage multiple types of campaigns and just generate scripts with those we need for a specific promo.

Thanks so much - and very good work. I use this in combination with a liquid snippet in the theme to display the promos/free gifts popups and works very well.

**Comment by chrisjcalderon** [comment]
Question: 

In the Buy Item Selector/Line Item Selector, is there a to add an option to check the Line Item product price?

One of my campaigns would like to run like this:

Get a Free Barracuda Case with the purchase of Any Paddle $50 or more

So, it would be configured with Product Type = Paddle however I can't do the price part - in this case, I was able to get away by adding another selector with product id not equal to a list of <50 paddles, but is a bit more complex to setup and maintain.

Thoughts?

**Comment by jgodson** [comment]
Thanks for the suggestion. Re-ordering campaigns is definitely something that's been on my to-do list for awhile. I like the idea of turning them on and off as well. Will add that to my list as well.

As for your question: there is not a way to do that there currently, but it probably makes sense to have that as an option. There's another work around I can think of that might be less work than adding all the id's, but this is easy enough to add that I'll get in in right away.

Again, thanks for the this, appreciate the input!

**Comment by jgodson** [comment]
Just to let you know, I just added the concept of `Active` campaigns. Will work on being able to re-order them next 👍

**Comment by chrisjcalderon** [comment]
That is fantastic! thanks so much!  Now I can keep all the campaigns I normally use, and choose the ones I need at any given time.

**Comment by jgodson** [comment]
Hey Christian, I just added the ability to sort the campaigns so I'm going to close out this issue now 🎉

**Comment by chrisjcalderon** [comment]
Thanks so much!! I like how is easier to deactivate/activate campaigns by clicking on the labels as well.
