### ISSUE TITLE
Feature request: Bundle option, "Buy X & Y for $Z"

### ISSUE THREAD

**Issue by brandoncontrav** [jgodson/shopify-script-creator#82]
Hello, tried doing this with the Bundle script option, but it looks like it can't. 

We have item X for $40, and item Y for $30, but want to create a bundle discount where the total is $50 when they are bundled. 

It looks like the current Script editor only allows for % or $ off, not setting a "new total price". 

Would it be possible to add this feature?

**Comment by jgodson** [comment]
Hello, I did build something like that [a long time ago](https://github.com/jgodson/shopify-script-creator/pull/4) unfortunately it didn't have great results across the board at the time. I could look at adding it In if I have some time, but also feel free to use the code in that PR and paste it into your script to check it out!

**Comment by jgodson** [comment]
Hey @brandoncontrav , sorry I never got to this! With the deprecation of Scripts next August, I'm not planning any new features at this point.
