### ISSUE TITLE
Feature Request: Recognize Selling Plans

### ISSUE THREAD

**Issue by rb-dante** [jgodson/shopify-script-creator#83]
Would love to see a cart qualifier for if there are subscription items in the cart or not. Taken a step further, only applying discounts to one-time or subscription versions of specific product/variant.

**Comment by jgodson** [comment]
Hello, I think that should already be present. There is a line item selector for subscription items.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/12747574/226642470-f7d25305-a3d2-4a89-ab16-7bc1af69f5da.png">
