### ISSUE TITLE
Will there be a version of this for Shopify Functions?

### ISSUE THREAD

**Issue by csdesign** [jgodson/shopify-script-creator#85]
Since Script Editor is being discontinued, will there be a tool to write Shopify Functions that works similar to your Script Creator app?  I don't write in Ruby, so the Script Creator has been a life saver for writing advanced scripts.  I am hoping to see something like this for Functions.

**Comment by jgodson** [comment]
Hi there! I'm really glad the Script Creator has been useful for you!

I also hope to see something like this for functions, however I can't say that I'm planning on working on that myself. The Script Creator will be around as long as scripts are supported, and I'm hoping that some other solutions will be available by the time support for scripts ends to replace it.
