### ISSUE TITLE
Feature Request: And/or Shipping Name/Rate

### ISSUE THREAD

**Issue by shaunkip** [jgodson/shopify-script-creator#88]
Thanks for this creator, it's amazing.

I have a use case I'm hoping you can incorporate or advise please.

I am using a script to look for 'Standard Delivery' and rate >'3.95' to reduce the price and it is working exactly as expected.

I am now finding myself in a position where I also need to look for 'Fast track' and rate >'1.95 at the same time, I can only have 1 script running and not sure if there is a way to set this up?

Looking for Standard delivery >3.95 and/or fast track delivery >1.95

Thanks in advance.

**Comment by jgodson** [comment]
Hello 👋🏻. On the right side, there is a button beside `Campaigns` to `Create new`. You should be able to fill out the form again and it will include both in the same script when you generate it! Let me know if that helps!

**Comment by shaunkip** [comment]
Thank you,

I tried the new script out but it is coming up with an error:

![Screenshot 2023-06-15 085751](https://github.com/jgodson/shopify-script-creator/assets/136587148/1507bc13-55a5-419d-9a38-858a52c303a4)

**Comment by shaunkip** [comment]
Thanks Jason,

I ran the script but the necessary changes were only made to 1 of the applicable shipping methods 'Standard Delivery' and when both 'Standard Delivery' and 'Fast Track Delivery (1 - 2 Days)' were options there was no discount applied to fast track?

`# GENERATED BY THE SHOPIFY SCRIPT CREATOR APP
class Campaign
  def initialize(condition, *qualifiers)
    @condition = (condition.to_s + '?').to_sym
    @qualifiers = PostCartAmountQualifier ? [] : [] rescue qualifiers.compact
    @line_item_selector = qualifiers.last unless @line_item_selector
    qualifiers.compact.each do |qualifier|
      is_multi_select = qualifier.instance_variable_get(:@conditions).is_a?(Array)
      if is_multi_select
        qualifier.instance_variable_get(:@conditions).each do |nested_q|
          @post_amount_qualifier = nested_q if nested_q.is_a?(PostCartAmountQualifier)
          @qualifiers << qualifier
        end
      else
        @post_amount_qualifier = qualifier if qualifier.is_a?(PostCartAmountQualifier)
        @qualifiers << qualifier
      end
    end if @qualifiers.empty?
  end

  def qualifies?(cart)
    return true if @qualifiers.empty?
    @unmodified_line_items = cart.line_items.map do |item|
      new_item = item.dup
      new_item.instance_variables.each do |var|
        val = item.instance_variable_get(var)
        new_item.instance_variable_set(var, val.dup) if val.respond_to?(:dup)
      end
      new_item
    end if @post_amount_qualifier
    @qualifiers.send(@condition) do |qualifier|
      is_selector = false
      if qualifier.is_a?(Selector) || qualifier.instance_variable_get(:@conditions).any? { |q| q.is_a?(Selector) }
        is_selector = true
      end rescue nil
      if is_selector
        raise "Missing line item match type" if @li_match_type.nil?
        cart.line_items.send(@li_match_type) do |item|
          next false if item.nil?
          qualifier.match?(item)
        end
      else
        qualifier.match?(cart, @line_item_selector)
      end
    end
  end

  def run_with_hooks(cart)
    before_run(cart) if respond_to?(:before_run)
    run(cart)
    after_run(cart)
  end

  def after_run(cart)
    @discount.apply_final_discount if @discount && @discount.respond_to?(:apply_final_discount)
    revert_changes(cart) unless @post_amount_qualifier.nil? || @post_amount_qualifier.match?(cart)
  end

  def revert_changes(cart)
    cart.instance_variable_set(:@line_items, @unmodified_line_items)
  end
end

class ShippingDiscount < Campaign
  def initialize(condition, customer_qualifier, cart_qualifier, li_match_type, line_item_qualifier, rate_selector, discount)
    super(condition, customer_qualifier, cart_qualifier, line_item_qualifier)
    @li_match_type = (li_match_type.to_s + '?').to_sym
    @rate_selector = rate_selector
    @discount = discount
  end

  def run(rates, cart)
    raise "Campaign requires a discount" unless @discount
    return unless qualifies?(cart)
    rates.each do |rate|
      next unless @rate_selector.nil? || @rate_selector.match?(rate)
      @discount.apply(rate)
    end
  end
end

class AndSelector
  def initialize(*conditions)
    @conditions = conditions.compact
  end

  def match?(item, selector = nil)
    @conditions.all? do |condition|
      if selector
        condition.match?(item, selector)
      else
        condition.match?(item)
      end
    end
  end
end

class Selector
  def partial_match(match_type, item_info, possible_matches)
    match_type = (match_type.to_s + '?').to_sym
    if item_info.kind_of?(Array)
      possible_matches.any? do |possibility|
        item_info.any? do |search|
          search.send(match_type, possibility)
        end
      end
    else
      possible_matches.any? do |possibility|
        item_info.send(match_type, possibility)
      end
    end
  end
end

class RateNameSelector < Selector
  def initialize(match_type, match_condition, names)
    @match_condition = match_condition
    @invert = match_type == :does_not
    @names = names.map(&:downcase)
  end

  def match?(shipping_rate)
    name = shipping_rate.name.downcase
    case @match_condition
      when :match
        return @invert ^ @names.include?(name)
      else
        return @invert ^ partial_match(@match_condition, name, @names)
    end
  end
end

class RatePriceSelector < Selector
  def initialize(comparison_type, amount)
    @comparison_type = comparison_type
    @amount = Money.new(cents: amount * 100)
  end

  def match?(shipping_rate)
    compare_amounts(shipping_rate.price, @comparison_type, @amount)
  end

  def compare_amounts(compare, comparison_type, compare_to)
    case comparison_type
      when :greater_than
        return compare > compare_to
      when :greater_than_or_equal
        return compare >= compare_to
      when :less_than
        return compare < compare_to
      when :less_than_or_equal
        return compare <= compare_to
      when :equal_to
        return compare == compare_to
      else
        raise "Invalid comparison type"
    end
  end
end

class PercentageDiscount
  def initialize(percent, message)
    @percent = Decimal.new(percent) / 100
    @message = message
  end

  def apply(rate)
    rate.apply_discount(rate.price * @percent, { message: @message })
  end
end

CAMPAIGNS = [
  ShippingDiscount.new(
    :all,
    nil,
    nil,
    :any,
    nil,
    AndSelector.new(
      RateNameSelector.new(
        :does,
        :match,
        ["Standard Delivery"]
      ),
      RatePriceSelector.new(
        :greater_than,
        3.95
      ),
      nil
    ),
    PercentageDiscount.new(
      50,
      ""
    )
  ),
  ShippingDiscount.new(
    :all,
    nil,
    nil,
    :any,
    nil,
    AndSelector.new(
      RateNameSelector.new(
        :does,
        :match,
        ["Fast Track Delivery (1 - 2 Days)"]
      ),
      RatePriceSelector.new(
        :greater_than,
        1.95
      ),
      nil
    ),
    PercentageDiscount.new(
      50,
      ""
    )
  )
].freeze

CAMPAIGNS.each do |campaign|
  campaign.run(Input.shipping_rates, Input.cart)
end

Output.shipping_rates = Input.shipping_rates`

**Comment by shaunkip** [comment]
Perfect, thank you @jgodson!

**Comment by jgodson** [comment]
No problem!
