### ISSUE TITLE
Bug: VariantSkuSelector RuntimeError when some line items don't have SKUs (undefined method 'downcase' for nil)

### ISSUE THREAD

**Issue by binarymonkey84** [jgodson/shopify-script-creator#90]
Hi there

Thanks for maintaining such a great tool. We use it a lot.

I came across this error today which was preventing a Black Friday campaign from running properly.

The issue is that if you have configured a variant selector based on SKU in Script Creator, then a `RuntimeError` is thrown if any of the cart line items do not have a SKU set on them.

The `RuntimeError` message is `undefined method 'downcase' for nil`.

See below screenshot:

![image](https://github.com/jgodson/shopify-script-creator/assets/20354825/b71112ae-b15c-4c14-9613-6785ca5d388c)

Related source file lines:

- https://github.com/jgodson/shopify-script-creator/blob/9ab33ba7565801df51e46d60914fcfdbaa7d10fa/src/scripts/common.js#L648
- https://github.com/jgodson/shopify-script-creator/blob/9ab33ba7565801df51e46d60914fcfdbaa7d10fa/ruby_scripts/common/variant_sku_selector.rb#L9

Hopefully this is a relatively simple fix!

**Comment by jgodson** [comment]
Thank you for reporting the issue! That should be a simple fix, something like:

```
def match?(line_item)
  return false if line_item.variant.skus.empty?
  ...
end
```

I can hopefully find some time to get this fix in!

**Comment by jgodson** [comment]
Should be fixed up now!

**Comment by jgodson** [comment]
Sorry, I made a mistake the last fix. *Now* it should be fixed 😂 .
