### ISSUE TITLE
Cart Qualifier - "Multi-Select - Meets all conditions" with "Discounted Cart Subtotal (applied by scripts)" not working

### ISSUE THREAD

**Issue by binarymonkey84** [jgodson/shopify-script-creator#96]
I noticed what looks like a bug - as follows:

## Steps to reproduce

1. Create a new campaign type "Conditional Discount" which uses a Cart Qualifier of "Multi-Select - Meets all conditions".
2. Add two conditions, each one being "Discounted Cart Subtotal (applied by scripts)". These conditions should restrict the discount to only apply between X and Y cart subtotal values (e.g. £60-89.99)
3. Add discounted item selector, and specify a SKU - apply discount a maximum of 1 time and set to 100%

Config file to reproduce example:

`{"version":"ShopifyScriptCreatorFile-V0.34.2","type":"line_item","campaigns":[{"name":"ConditionalDiscount","active":true,"label":"GWP Tier 1","id":11,"inputs":[":all",{"name":"none"},{"name":"AndSelector","inputs":[{"name":"PostCartAmountQualifier","inputs":[":greater_than_or_equal",60]},{"name":"PostCartAmountQualifier","inputs":[":less_than_or_equal",89.99]},{"name":"none"}]},{"name":"VariantSkuSelector","inputs":[":does",":match","[\"SBFCW200\"]"]},{"name":"PercentageDiscount","inputs":[100,"\"Free Gift when you spend £60-80.99\""]},1]}]}`

![image](https://github.com/jgodson/shopify-script-creator/assets/20354825/d806a1e8-fe62-479f-a29d-0d884e490dd1)

## Expected result

The discount should only be applied if the cart subtotal is within £60-89.99 after discounts are / would have been applied.

## Observed behaviour

The discount is applied to the cart subtotal, rather than the cart subtotal after discounts have been applied by scripts.

E.g. The customer is only actually spending £49, but they still get the discounted item. They need to be spending £60-89.99.

![image](https://github.com/jgodson/shopify-script-creator/assets/20354825/c48618ec-63b5-45cd-8cd1-e7f69d82f135)

## Notes

This behaviour works fine when using "Discounted Cart Subtotal (applied by scripts)" cart qualifier, but not when using "Multi-Select - Meets all conditions" with "Discounted Cart Subtotal (applied by scripts)".

**Comment by jgodson** [comment]
Hey @binarymonkey84 👋🏻. Thank you for the bug report and the excellent issue write up!

I think the issue is that I account for [one PostCartAmountQualifier](https://github.com/jgodson/shopify-script-creator/blob/master/ruby_scripts/common/campaign.rb#L10) (the `Discounted cart subtotal` that you are using there) so the second one (<= 89.99) will be the only one that's checked and the cart in your example meets that. I don't think it should be a huge change to make this work properly as I can change that to an array of qualifiers instead. I will see if I can get to this sometime!

**Comment by jgodson** [comment]
Sorry for the delay, but I finally got to this. It should be fixed in the most recent release (V0.34.3)
